import type { DashboardStyles, DashboardThemeColors } from '../../types/dashboard';

export const themeTokens: Record<'dark' | 'light', DashboardThemeColors> = {
  dark: {
    name: 'dark',
    pageBackground: 'var(--planto-page-bg)',
    shell: 'var(--planto-surface)',
    shellMuted: 'var(--planto-surface-muted)',
    shellRaised: 'var(--planto-surface-raised)',
    border: 'var(--planto-border)',
    borderStrong: 'var(--planto-border-strong)',
    borderAccent: 'var(--planto-border-accent)',
    text: 'var(--planto-text)',
    textMuted: 'var(--planto-muted)',
    textStrong: 'var(--planto-text-strong)',
    accent: 'var(--planto-accent)',
    accentText: 'var(--planto-accent-text)',
    accentSoft: 'var(--planto-accent-soft)',
    accentMuted: 'var(--planto-accent-muted)',
    danger: 'var(--planto-danger)',
    dangerBg: 'var(--planto-danger-bg)',
    dangerText: 'var(--planto-danger-text)',
    successBg: 'var(--planto-success-bg)',
    successText: 'var(--planto-success-text)',
    errorBg: 'var(--planto-error-bg)',
    errorText: 'var(--planto-error-text)',
    overlay: 'var(--planto-overlay)',
    inputBg: 'var(--planto-input-bg)',
    tokenBg: 'var(--planto-token-bg)',
  },
  light: {
    name: 'light',
    pageBackground: 'var(--planto-light-page-bg)',
    shell: 'var(--planto-light-surface)',
    shellMuted: 'var(--planto-light-surface-muted)',
    shellRaised: 'var(--planto-light-surface-raised)',
    border: 'var(--planto-light-border)',
    borderStrong: 'var(--planto-light-border-strong)',
    borderAccent: 'var(--planto-light-border-accent)',
    text: 'var(--planto-light-text)',
    textMuted: 'var(--planto-light-muted)',
    textStrong: 'var(--planto-light-text-strong)',
    accent: 'var(--planto-light-accent)',
    accentText: 'var(--planto-light-accent-text)',
    accentSoft: 'var(--planto-light-accent-soft)',
    accentMuted: 'var(--planto-light-accent-muted)',
    danger: 'var(--planto-light-danger)',
    dangerBg: 'var(--planto-light-danger-bg)',
    dangerText: 'var(--planto-light-danger-text)',
    successBg: 'var(--planto-light-success-bg)',
    successText: 'var(--planto-light-success-text)',
    errorBg: 'var(--planto-light-error-bg)',
    errorText: 'var(--planto-light-error-text)',
    overlay: 'var(--planto-light-overlay)',
    inputBg: 'var(--planto-light-input-bg)',
    tokenBg: 'var(--planto-light-token-bg)',
  },
};

export function createDashboardStyles(colors: DashboardThemeColors, isCompact: boolean): DashboardStyles {
  return {
    page: {
      minHeight: '100vh',
      background: colors.pageBackground,
      color: colors.text,
      padding: isCompact ? '16px' : '20px',
      fontFamily: 'var(--font-inter), Inter, sans-serif',
    },
    pageShell: {
      maxWidth: '1440px',
      margin: '0 auto',
      display: 'grid',
      gap: '14px',
    },
    header: {
      display: 'flex',
      alignItems: isCompact ? 'flex-start' : 'center',
      justifyContent: 'space-between',
      flexDirection: isCompact ? 'column' : 'row',
      gap: '14px',
    },
    title: { margin: 0, fontSize: isCompact ? '2rem' : '2.4rem', color: colors.textStrong },
    subtitle: { margin: '6px 0 0', color: colors.textMuted, fontSize: '0.96rem' },
    headerActions: {
      display: 'flex',
      gap: '10px',
      alignItems: 'center',
      width: isCompact ? '100%' : 'auto',
      justifyContent: isCompact ? 'space-between' : 'flex-end',
      flexWrap: 'wrap',
    },
    headerTokenBar: {
      display: 'inline-flex',
      alignItems: 'center',
      gap: '8px',
      border: `1px solid ${colors.borderStrong}`,
      borderRadius: '14px',
      padding: '5px',
      background: colors.shellMuted,
      width: isCompact ? '100%' : 'fit-content',
      maxWidth: isCompact ? '100%' : '760px',
      minWidth: isCompact ? '100%' : '360px',
      boxSizing: 'border-box',
    },
    headerTokenCode: {
      flex: '0 1 auto',
      minWidth: isCompact ? 0 : '280px',
      maxWidth: isCompact ? '100%' : '620px',
      borderRadius: '10px',
      padding: '8px 10px',
      background: colors.tokenBg,
      color: colors.textStrong,
      fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Consolas, monospace',
      fontSize: '0.76rem',
      whiteSpace: 'nowrap',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    headerTokenHint: {
      flex: '0 1 auto',
      minWidth: isCompact ? 0 : '260px',
      maxWidth: isCompact ? '100%' : '360px',
      borderRadius: '10px',
      padding: '8px 10px',
      color: colors.textMuted,
      fontSize: '0.8rem',
      whiteSpace: 'nowrap',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    notice: {
      justifySelf: 'end',
      borderRadius: '999px',
      padding: '6px 12px',
      background: colors.successBg,
      color: colors.successText,
      fontSize: '0.8rem',
      fontWeight: 600,
      border: `1px solid ${colors.borderAccent}`,
    },
    errorBanner: {
      borderRadius: '12px',
      padding: '10px 12px',
      background: colors.errorBg,
      color: colors.errorText,
      border: `1px solid ${colors.danger}`,
      fontSize: '0.9rem',
    },
    loader: {
      padding: '18px 0',
      color: colors.textMuted,
      fontSize: '0.95rem',
    },
    grid: {
      display: 'grid',
      gap: '14px',
      gridTemplateColumns: isCompact ? '1fr' : '300px minmax(420px, 1fr) 360px',
      alignItems: 'start',
    },
    leftPanel: {
      background: colors.shell,
      border: `1px solid ${colors.border}`,
      borderRadius: '18px',
      padding: '14px',
      display: 'grid',
      gap: '12px',
    },
    centerPanel: {
      background: colors.shell,
      border: `1px solid ${colors.border}`,
      borderRadius: '18px',
      padding: '14px',
      display: 'grid',
      gap: '14px',
    },
    rightColumn: {
      display: 'grid',
      gap: '14px',
      alignSelf: 'start',
    },
    rightPanel: {
      background: colors.shell,
      border: `1px solid ${colors.border}`,
      borderRadius: '18px',
      padding: '14px',
      display: 'grid',
      gap: '12px',
    },
    panelTitle: {
      margin: 0,
      color: colors.textStrong,
      fontSize: '1.06rem',
    },
    cardBlock: {
      border: `1px solid ${colors.border}`,
      borderRadius: '14px',
      padding: '12px',
      background: colors.shellMuted,
      display: 'grid',
      gap: '12px',
    },
    formCard: {
      borderBottom: `1px solid ${colors.border}`,
      padding: '0 0 14px',
    },
    formCardHeader: {
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: '10px',
      padding: '8px 0',
    },
    formCardBody: {
      display: 'grid',
      gap: '12px',
      padding: '12px 0 0',
    },
    cardTitle: { margin: 0, fontSize: '0.96rem', color: colors.textStrong },
    sectionDescription: {
      margin: '2px 0 0',
      color: colors.textMuted,
      fontSize: '0.84rem',
      lineHeight: 1.5,
    },
    briefingH1: {
      margin: 0,
      color: colors.textStrong,
      fontSize: isCompact ? '1.5rem' : '1.7rem',
      lineHeight: 1.2,
      fontWeight: 800,
    },
    briefingH2: {
      margin: 0,
      color: colors.textStrong,
      fontSize: '1.1rem',
      lineHeight: 1.3,
      fontWeight: 700,
    },
    collapseButton: {
      width: '34px',
      height: '34px',
      display: 'inline-flex',
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: '10px',
      border: `1px solid ${colors.borderStrong}`,
      background: colors.shell,
      cursor: 'pointer',
      padding: 0,
    },
    formGrid: {
      display: 'grid',
      gap: '22px',
    },
    label: {
      display: 'grid',
      gap: '6px',
      fontSize: '0.82rem',
      color: colors.textMuted,
    },
    input: {
      border: `1px solid ${colors.borderStrong}`,
      borderRadius: '10px',
      background: colors.inputBg,
      color: colors.text,
      padding: '10px 12px',
      fontSize: '0.92rem',
      width: '100%',
      outline: 'none',
      boxSizing: 'border-box',
    },
    textarea: {
      border: `1px solid ${colors.borderStrong}`,
      borderRadius: '10px',
      background: colors.inputBg,
      color: colors.text,
      padding: '10px 12px',
      fontSize: '0.9rem',
      width: '100%',
      resize: 'vertical',
      outline: 'none',
      boxSizing: 'border-box',
      minHeight: '92px',
    },
    primaryButton: {
      border: 'none',
      borderRadius: '10px',
      padding: '10px 12px',
      background: colors.accent,
      color: colors.accentText,
      cursor: 'pointer',
      fontWeight: 700,
      fontSize: '0.86rem',
    },
    secondaryButton: {
      border: `1px solid ${colors.borderStrong}`,
      borderRadius: '10px',
      padding: '9px 12px',
      background: colors.shell,
      color: colors.text,
      cursor: 'pointer',
      fontWeight: 600,
      fontSize: '0.84rem',
    },
    ghostButton: {
      border: `1px solid ${colors.borderStrong}`,
      borderRadius: '10px',
      padding: '9px 12px',
      background: 'transparent',
      color: colors.text,
      cursor: 'pointer',
      fontSize: '0.84rem',
    },
    iconButton: {
      display: 'inline-flex',
      alignItems: 'center',
      gap: '8px',
      border: `1px solid ${colors.borderStrong}`,
      borderRadius: '10px',
      padding: '9px 12px',
      background: colors.shell,
      color: colors.text,
      cursor: 'pointer',
      fontSize: '0.84rem',
      fontWeight: 600,
    },
    iconOnlyButton: {
      width: '38px',
      height: '38px',
      minWidth: '38px',
      flex: '0 0 38px',
      display: 'inline-flex',
      alignItems: 'center',
      justifyContent: 'center',
      border: `1px solid ${colors.borderStrong}`,
      borderRadius: '12px',
      padding: 0,
      background: colors.shell,
      color: colors.text,
      cursor: 'pointer',
    },
    quickNav: {
      display: 'grid',
      gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
      gap: '8px',
      width: '100%',
    },
    quickNavLink: {
      display: 'inline-flex',
      alignItems: 'center',
      justifyContent: 'center',
      width: '100%',
      minHeight: '42px',
      borderRadius: '10px',
      border: `1px solid ${colors.borderStrong}`,
      background: colors.shell,
      color: colors.text,
      padding: '10px 12px',
      fontSize: '0.84rem',
      fontWeight: 700,
      textDecoration: 'none',
      boxSizing: 'border-box',
    },
    dangerButton: {
      border: `1px solid ${colors.danger}`,
      borderRadius: '10px',
      padding: '9px 12px',
      background: colors.dangerBg,
      color: colors.dangerText,
      cursor: 'pointer',
      fontSize: '0.82rem',
      fontWeight: 700,
    },
    dangerIconButton: {
      width: '34px',
      height: '34px',
      display: 'inline-flex',
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: '10px',
      border: `1px solid ${colors.danger}`,
      background: colors.dangerBg,
      color: colors.dangerText,
      cursor: 'pointer',
      padding: 0,
      flex: '0 0 auto',
    },
    list: {
      display: 'grid',
      gap: '8px',
    },
    listItem: {
      border: `1px solid ${colors.border}`,
      borderRadius: '10px',
      padding: '10px',
      background: colors.shellMuted,
      display: 'grid',
      gap: '4px',
    },
    listItemInline: {
      display: 'flex',
      justifyContent: 'space-between',
      alignItems: 'center',
      gap: '8px',
      flexWrap: 'wrap',
      border: `1px solid ${colors.border}`,
      borderRadius: '10px',
      padding: '10px',
      background: colors.shellMuted,
    },
    listTitle: {
      margin: 0,
      fontSize: '0.9rem',
      color: colors.textStrong,
      fontWeight: 700,
    },
    smallText: {
      margin: 0,
      fontSize: '0.78rem',
      color: colors.textMuted,
      wordBreak: 'break-word',
    },
    briefingIntro: {
      display: 'grid',
      gap: '12px',
      borderBottom: `1px solid ${colors.border}`,
      padding: '0 0 14px',
    },
    briefingIntroHeader: {
      display: 'flex',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
      gap: '12px',
    },
    briefingSubtitle: {
      margin: '6px 0 0',
      color: colors.textMuted,
      fontSize: '0.92rem',
      lineHeight: 1.5,
    },
    briefingBodyText: {
      margin: '8px 0 0',
      color: colors.text,
      fontSize: '0.9rem',
      lineHeight: 1.65,
    },
    briefingList: {
      margin: '8px 0 0',
      paddingLeft: '18px',
      display: 'grid',
      gap: '6px',
      color: colors.text,
      fontSize: '0.88rem',
      lineHeight: 1.55,
    },
    fieldBlock: {
      display: 'grid',
      gap: '10px',
      paddingBottom: '14px',
      borderBottom: `1px solid ${colors.border}`,
    },
    fieldHeading: {
      margin: 0,
      fontSize: '1rem',
      color: colors.textStrong,
      lineHeight: 1.45,
      fontWeight: 700,
    },
    fieldPrompt: {
      margin: 0,
      fontSize: '0.94rem',
      color: colors.text,
      lineHeight: 1.6,
      fontWeight: 700,
    },
    fieldDescription: {
      margin: 0,
      fontSize: '0.9rem',
      color: colors.textMuted,
      lineHeight: 1.55,
    },
    tokenBox: {
      border: `1px dashed ${colors.borderAccent}`,
      borderRadius: '12px',
      padding: '10px',
      background: colors.tokenBg,
    },
    code: {
      display: 'block',
      fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Consolas, monospace',
      fontSize: '0.8rem',
      color: colors.textStrong,
      wordBreak: 'break-all',
      marginTop: '4px',
    },
    avatarArea: {
      display: 'grid',
      alignItems: 'center',
      justifyItems: 'center',
      gap: '10px',
      padding: '4px 0 8px',
    },
    avatarButton: {
      width: '132px',
      height: '132px',
      borderRadius: '999px',
      border: `2px solid ${colors.borderAccent}`,
      padding: 0,
      position: 'relative',
      background: colors.shellRaised,
      cursor: 'pointer',
      boxShadow: '0 12px 28px rgba(15, 23, 42, 0.22)',
    },
    avatarImage: {
      width: '100%',
      height: '100%',
      objectFit: 'cover',
      display: 'block',
      borderRadius: '999px',
    },
    avatarCameraBadge: {
      position: 'absolute',
      right: '-6px',
      bottom: '8px',
      width: '42px',
      height: '42px',
      borderRadius: '999px',
      display: 'grid',
      placeItems: 'center',
      background: colors.shell,
      border: `1px solid ${colors.borderStrong}`,
      boxShadow: '0 8px 18px rgba(15, 23, 42, 0.24)',
    },
    avatarGreeting: {
      margin: 0,
      color: colors.textStrong,
      fontSize: '0.98rem',
      fontWeight: 700,
      textAlign: 'center',
    },
    hiddenInput: {
      display: 'none',
    },
    countBadge: {
      width: 'fit-content',
      borderRadius: '999px',
      border: `1px solid ${colors.borderAccent}`,
      padding: '5px 10px',
      fontSize: '0.76rem',
      color: colors.accentMuted,
      background: colors.shell,
      fontWeight: 700,
    },
    uploadDropzone: {
      width: '100%',
      minHeight: '142px',
      border: `1px dashed ${colors.borderStrong}`,
      borderRadius: '14px',
      background: colors.inputBg,
      color: colors.textMuted,
      display: 'grid',
      placeItems: 'center',
      gap: '10px',
      padding: '18px',
      cursor: 'pointer',
      textAlign: 'center',
      boxSizing: 'border-box',
    },
    uploadIconFrame: {
      width: '58px',
      height: '58px',
      display: 'grid',
      placeItems: 'center',
      borderRadius: '16px',
      background: colors.shell,
      border: `1px solid ${colors.border}`,
    },
    uploadDropzoneText: {
      fontSize: '0.86rem',
      color: colors.textMuted,
      lineHeight: 1.5,
    },
    uploadBrowseText: {
      color: colors.accentMuted,
      fontWeight: 800,
      textDecoration: 'underline',
    },
    uploadSelectedFile: {
      display: 'flex',
      alignItems: 'center',
      gap: '10px',
      border: `1px solid ${colors.border}`,
      borderRadius: '12px',
      padding: '10px',
      background: colors.shellMuted,
    },
    uploadFileIcon: {
      width: '42px',
      height: '42px',
      border: `1px solid ${colors.borderStrong}`,
      borderRadius: '10px',
      display: 'grid',
      placeItems: 'center',
      color: colors.textMuted,
      fontSize: '0.62rem',
      fontWeight: 800,
      background: colors.shell,
    },
    uploadFileDetails: {
      minWidth: 0,
      display: 'grid',
      gap: '3px',
    },
    entryButton: {
      border: `1px solid ${colors.border}`,
      borderRadius: '10px',
      padding: '10px',
      background: colors.shellMuted,
      color: colors.text,
      display: 'grid',
      gap: '4px',
      cursor: 'pointer',
      textAlign: 'left',
    },
    entryButtonActive: {
      border: `1px solid ${colors.borderAccent}`,
      borderRadius: '10px',
      padding: '10px',
      background: colors.accentSoft,
      color: colors.text,
      display: 'grid',
      gap: '4px',
      cursor: 'pointer',
      textAlign: 'left',
    },
    entryBadge: {
      border: `1px solid ${colors.borderAccent}`,
      borderRadius: '999px',
      padding: '1px 8px',
      fontSize: '0.7rem',
      color: colors.accentMuted,
      background: colors.shell,
    },
  };
}
