import type { DashboardStyles, DashboardThemeColors } from '../../types/dashboard';

export const themeTokens: Record<'dark' | 'light', DashboardThemeColors> = {
  dark: {
    name: 'dark',
    pageBackground: 'var(--planto-page-bg)',
    shell: 'var(--planto-surface)',
    shellMuted: 'var(--planto-surface-muted)',
    shellRaised: 'var(--planto-surface-raised)',
    border: 'var(--planto-border)',
    borderStrong: 'var(--planto-border-strong)',
    borderAccent: 'var(--planto-border-accent)',
    text: 'var(--planto-text)',
    textMuted: 'var(--planto-muted)',
    textStrong: 'var(--planto-text-strong)',
    accent: 'var(--planto-accent)',
    accentText: 'var(--planto-accent-text)',
    accentSoft: 'var(--planto-accent-soft)',
    accentMuted: 'var(--planto-accent-muted)',
    danger: 'var(--planto-danger)',
    dangerBg: 'var(--planto-danger-bg)',
    dangerText: 'var(--planto-danger-text)',
    successBg: 'var(--planto-success-bg)',
    successText: 'var(--planto-success-text)',
    errorBg: 'var(--planto-error-bg)',
    errorText: 'var(--planto-error-text)',
    overlay: 'var(--planto-overlay)',
    inputBg: 'var(--planto-input-bg)',
    tokenBg: 'var(--planto-token-bg)',
  },
  light: {
    name: 'light',
    pageBackground: 'var(--planto-light-page-bg)',
    shell: 'var(--planto-light-surface)',
    shellMuted: 'var(--planto-light-surface-muted)',
    shellRaised: 'var(--planto-light-surface-raised)',
    border: 'var(--planto-light-border)',
    borderStrong: 'var(--planto-light-border-strong)',
    borderAccent: 'var(--planto-light-border-accent)',
    text: 'var(--planto-light-text)',
    textMuted: 'var(--planto-light-muted)',
    textStrong: 'var(--planto-light-text-strong)',
    accent: 'var(--planto-light-accent)',
    accentText: 'var(--planto-light-accent-text)',
    accentSoft: 'var(--planto-light-accent-soft)',
    accentMuted: 'var(--planto-light-accent-muted)',
    danger: 'var(--planto-light-danger)',
    dangerBg: 'var(--planto-light-danger-bg)',
    dangerText: 'var(--planto-light-danger-text)',
    successBg: 'var(--planto-light-success-bg)',
    successText: 'var(--planto-light-success-text)',
    errorBg: 'var(--planto-light-error-bg)',
    errorText: 'var(--planto-light-error-text)',
    overlay: 'var(--planto-light-overlay)',
    inputBg: 'var(--planto-light-input-bg)',
    tokenBg: 'var(--planto-light-token-bg)',
  },
};

export function createDashboardStyles(colors: DashboardThemeColors, viewportWidth: number): DashboardStyles {
  const isCompact = viewportWidth < 980;
  const isWide = viewportWidth >= 1280;
  const isMedium = viewportWidth >= 980 && viewportWidth < 1280;

  return {
    page: {
      minHeight: '100vh',
      background: colors.pageBackground,
      color: colors.text,
      padding: 0,
      fontFamily: '"Inter", "Segoe UI", -apple-system, BlinkMacSystemFont, sans-serif',
    },
    pageShell: {
      maxWidth: '1880px',
      margin: '0 auto',
      display: 'grid',
      gap: '10px',
      padding: isCompact ? '10px' : '16px',
    },
    header: {
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'space-between',
      flexDirection: 'row',
      gap: '8px',
      background: colors.name === 'light' ? '#ffffff' : colors.shell,
      border: `1px solid ${colors.border}`,
      borderRadius: '8px',
      padding: isCompact ? '10px 12px' : '12px 14px',
      boxShadow: colors.name === 'light' ? '0 10px 24px rgba(22, 16, 8, 0.05)' : '0 10px 24px rgba(0, 0, 0, 0.25)',
      position: 'static',
      top: 0,
      zIndex: 0,
    },
    headerLeading: {
      display: 'flex',
      alignItems: 'center',
      gap: '8px',
      minWidth: 0,
    },
    title: {
      margin: 0,
      fontSize: isCompact ? '1.22rem' : '1.34rem',
      color: colors.textStrong,
      fontWeight: 800,
      letterSpacing: '-0.01em',
      whiteSpace: 'nowrap',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    subtitle: { margin: '6px 0 0', color: colors.textMuted, fontSize: '0.96rem' },
    headerActions: {
      display: 'flex',
      gap: '8px',
      alignItems: 'center',
      width: 'auto',
      justifyContent: 'flex-end',
      flexWrap: 'nowrap',
    },
    headerTokenBar: {
      display: 'inline-flex',
      alignItems: 'center',
      gap: '8px',
      border: `1px solid ${colors.borderStrong}`,
      borderRadius: '8px',
      padding: '6px',
      background: colors.inputBg,
      width: '100%',
      maxWidth: '100%',
      minWidth: 0,
      boxSizing: 'border-box',
    },
    headerTokenCode: {
      flex: '0 1 auto',
      minWidth: 0,
      maxWidth: '100%',
      borderRadius: '6px',
      padding: '8px 9px',
      background: colors.tokenBg,
      color: colors.textStrong,
      fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Consolas, monospace',
      fontSize: '0.74rem',
      whiteSpace: 'nowrap',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    headerTokenHint: {
      flex: '0 1 auto',
      minWidth: 0,
      maxWidth: '100%',
      borderRadius: '6px',
      padding: '8px 9px',
      color: colors.textMuted,
      fontSize: '0.76rem',
      whiteSpace: 'nowrap',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    notice: {
      justifySelf: 'end',
      borderRadius: 0,
      padding: '6px 10px',
      background: colors.successBg,
      color: colors.successText,
      fontSize: '0.8rem',
      fontWeight: 600,
      border: 'none',
    },
    errorBanner: {
      borderRadius: 0,
      padding: '10px 12px',
      background: colors.errorBg,
      color: colors.errorText,
      border: 'none',
      fontSize: '0.9rem',
    },
    loader: {
      padding: '18px 0',
      color: colors.textMuted,
      fontSize: '0.95rem',
    },
    workspace: {
      display: 'grid',
      gap: isCompact ? '10px' : '14px',
      gridTemplateColumns: isWide
        ? 'minmax(210px, 280px) minmax(0, 1fr) minmax(250px, 320px)'
        : isMedium
        ? 'minmax(0, 1.7fr) minmax(280px, 1fr)'
        : 'minmax(0, 1fr)',
      alignItems: 'start',
      position: 'relative',
      minHeight: 'calc(100vh - 22px)',
    },
    zoneNav: {
      display: 'grid',
      gap: '12px',
      alignSelf: 'start',
      position: isCompact ? 'static' : 'sticky',
      top: isCompact ? 'auto' : '10px',
      minWidth: 0,
      gridColumn: isWide ? '1' : isMedium ? '2' : '1',
    },
    zoneMain: {
      display: 'grid',
      gap: '12px',
      minWidth: 0,
      alignSelf: 'start',
      gridColumn: isWide ? '2' : '1',
    },
    mainPanelScroll: {
      display: 'grid',
      gap: '12px',
      minHeight: 0,
      maxHeight: isCompact ? 'none' : 'calc(100vh - 132px)',
      overflowY: isCompact ? 'visible' : 'auto',
      overflowX: 'hidden',
      paddingRight: isCompact ? 0 : '4px',
    },
    zoneSupport: {
      display: 'grid',
      gap: '12px',
      minWidth: 0,
      alignSelf: 'start',
      position: isCompact ? 'static' : 'sticky',
      top: isCompact ? 'auto' : '10px',
      gridColumn: isWide ? '3' : isMedium ? '2' : '1',
    },
    grid: {
      display: 'grid',
      gap: isCompact ? '10px' : '14px',
      gridTemplateColumns: '1fr',
      alignItems: 'start',
      position: 'relative',
    },
    leftPanel: {
      background: colors.shell,
      border: `1px solid ${colors.border}`,
      borderRadius: '8px',
      padding: '12px',
      display: 'grid',
      gap: '10px',
      maxHeight: 'none',
      overflow: 'auto',
      position: 'static',
      width: '100%',
    },
    centerPanel: {
      background: 'transparent',
      border: 'none',
      borderRadius: 0,
      padding: isCompact ? '14px' : 'clamp(22px, 4vw, 56px)',
      display: 'grid',
      gap: '12px',
      minHeight: 0,
    },
    rightColumn: {
      display: 'grid',
      gap: '14px',
      alignSelf: 'start',
    },
    rightPanel: {
      background: 'transparent',
      border: 'none',
      borderRadius: 0,
      padding: 0,
      display: 'grid',
      gap: '10px',
    },
    panelCard: {
      border: `1px solid ${colors.border}`,
      borderRadius: '8px',
      background: colors.name === 'light' ? '#ffffff' : colors.shell,
      boxShadow: colors.name === 'light' ? '0 10px 24px rgba(22, 16, 8, 0.05)' : '0 10px 24px rgba(0, 0, 0, 0.25)',
      padding: isCompact ? '10px' : '12px',
      display: 'grid',
      gap: '10px',
      minWidth: 0,
    },
    panelCardHeader: {
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: '10px',
      borderBottom: `1px solid ${colors.border}`,
      paddingBottom: '8px',
    },
    panelCardHeaderGroup: {
      display: 'inline-flex',
      alignItems: 'center',
      gap: '6px',
      marginLeft: 'auto',
    },
    cardIconButton: {
      width: '30px',
      height: '30px',
      minWidth: '30px',
      display: 'inline-flex',
      alignItems: 'center',
      justifyContent: 'center',
      border: `1px solid ${colors.borderStrong}`,
      borderRadius: '7px',
      padding: 0,
      background: colors.name === 'light' ? '#ffffff' : colors.shellMuted,
      color: colors.text,
      cursor: 'pointer',
      fontSize: '0.82rem',
      fontWeight: 700,
      lineHeight: 1,
    },
    mainTabs: {
      display: 'flex',
      gap: '8px',
      flexWrap: 'wrap',
      alignItems: 'center',
    },
    mainTabButton: {
      border: `1px solid ${colors.borderStrong}`,
      borderRadius: '999px',
      padding: '6px 12px',
      background: colors.name === 'light' ? '#ffffff' : colors.shellMuted,
      color: colors.text,
      cursor: 'pointer',
      fontWeight: 600,
      fontSize: '0.8rem',
    },
    mainTabActive: {
      border: `1px solid ${colors.borderAccent}`,
      borderRadius: '999px',
      padding: '6px 12px',
      background: colors.name === 'light' ? 'var(--planto-light-nav-active)' : 'var(--planto-nav-active)',
      color: colors.textStrong,
      cursor: 'pointer',
      fontWeight: 700,
      fontSize: '0.8rem',
    },
    panelTitle: {
      margin: 0,
      color: colors.textStrong,
      fontSize: '0.92rem',
      fontWeight: 650,
    },
    cardBlock: {
      border: 'none',
      borderRadius: 0,
      padding: 0,
      background: 'transparent',
      display: 'grid',
      gap: '8px',
    },
    formCard: {
      border: `1px solid ${colors.border}`,
      borderRadius: '8px',
      background: colors.name === 'light' ? '#ffffff' : colors.shellMuted,
      padding: '12px',
    },
    formCardHeader: {
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: '10px',
      padding: 0,
    },
    formCardBody: {
      display: 'grid',
      gap: '12px',
      borderTop: `1px solid ${colors.border}`,
      padding: '12px 0 0',
    },
    cardTitle: { margin: 0, fontSize: '0.96rem', color: colors.textStrong },
    sectionDescription: {
      margin: '2px 0 0',
      color: colors.textMuted,
      fontSize: '0.84rem',
      lineHeight: 1.5,
    },
    briefingH1: {
      margin: 0,
      color: colors.textStrong,
      fontSize: isCompact ? '1.5rem' : '1.7rem',
      lineHeight: 1.2,
      fontWeight: 800,
    },
    briefingH2: {
      margin: 0,
      color: colors.textStrong,
      fontSize: '1.1rem',
      lineHeight: 1.3,
      fontWeight: 700,
    },
    collapseButton: {
      width: '34px',
      height: '34px',
      display: 'inline-flex',
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: '10px',
      border: `1px solid ${colors.borderStrong}`,
      background: colors.shell,
      cursor: 'pointer',
      padding: 0,
    },
    formGrid: {
      display: 'grid',
      gap: '14px',
    },
    label: {
      display: 'grid',
      gap: '6px',
      fontSize: '0.82rem',
      color: colors.textMuted,
    },
    input: {
      border: `1px solid ${colors.borderStrong}`,
      borderRadius: '8px',
      background: colors.name === 'light' ? '#ffffff' : colors.inputBg,
      color: colors.text,
      padding: '9px 10px',
      fontSize: '0.92rem',
      width: '100%',
      outline: 'none',
      boxSizing: 'border-box',
    },
    profileInput: {
      border: `1px solid ${colors.borderStrong}`,
      borderRadius: '8px',
      background: colors.name === 'light' ? '#ffffff' : colors.inputBg,
      color: colors.name === 'light' ? '#1f1b14' : colors.text,
      padding: '9px 10px',
      fontSize: '0.92rem',
      width: '100%',
      outline: 'none',
      boxSizing: 'border-box',
    },
    textarea: {
      border: `1px solid ${colors.borderStrong}`,
      borderRadius: '8px',
      background: colors.name === 'light' ? '#ffffff' : colors.inputBg,
      color: colors.text,
      padding: '9px 10px',
      fontSize: '0.9rem',
      width: '100%',
      resize: 'vertical',
      outline: 'none',
      boxSizing: 'border-box',
      minHeight: '92px',
    },
    primaryButton: {
      border: `1px solid ${colors.borderStrong}`,
      borderRadius: '8px',
      padding: '8px 10px',
      background: colors.accent,
      color: colors.accentText,
      cursor: 'pointer',
      fontWeight: 600,
      fontSize: '0.82rem',
    },
    secondaryButton: {
      border: `1px solid ${colors.borderStrong}`,
      borderRadius: '8px',
      padding: '8px 10px',
      background: colors.name === 'light' ? '#ffffff' : colors.shell,
      color: colors.text,
      cursor: 'pointer',
      fontWeight: 600,
      fontSize: '0.82rem',
    },
    ghostButton: {
      border: `1px solid ${colors.borderStrong}`,
      borderRadius: '8px',
      padding: '8px 10px',
      background: colors.name === 'light' ? '#ffffff' : 'transparent',
      color: colors.text,
      cursor: 'pointer',
      fontSize: '0.82rem',
      fontWeight: 600,
    },
    iconButton: {
      display: 'inline-flex',
      alignItems: 'center',
      gap: '8px',
      border: `1px solid ${colors.borderStrong}`,
      borderRadius: '8px',
      padding: '8px 10px',
      background: colors.name === 'light' ? '#ffffff' : colors.shell,
      color: colors.text,
      cursor: 'pointer',
      fontSize: '0.82rem',
      fontWeight: 600,
    },
    iconOnlyButton: {
      width: '34px',
      height: '34px',
      minWidth: '34px',
      flex: '0 0 34px',
      display: 'inline-flex',
      alignItems: 'center',
      justifyContent: 'center',
      border: `1px solid ${colors.borderStrong}`,
      borderRadius: '8px',
      padding: 0,
      background: colors.name === 'light' ? '#ffffff' : colors.shell,
      color: colors.text,
      cursor: 'pointer',
    },
    quickNav: {
      display: 'grid',
      gridTemplateColumns: '1fr',
      gap: '8px',
      width: '100%',
      maxWidth: '100%',
    },
    quickNavLink: {
      display: 'inline-flex',
      alignItems: 'center',
      justifyContent: 'flex-start',
      width: '100%',
      minHeight: '36px',
      borderRadius: '8px',
      border: `1px solid ${colors.borderStrong}`,
      background: colors.name === 'light' ? '#ffffff' : colors.shellMuted,
      color: colors.name === 'light' ? '#1f1b14' : colors.text,
      padding: '8px 10px',
      fontSize: '0.8rem',
      fontWeight: 600,
      textDecoration: 'none',
      boxSizing: 'border-box',
      cursor: 'pointer',
      gap: '8px',
    },
    quickNavLinkActive: {
      display: 'inline-flex',
      alignItems: 'center',
      justifyContent: 'flex-start',
      width: '100%',
      minHeight: '36px',
      borderRadius: '8px',
      border: `1px solid ${colors.borderAccent}`,
      background: colors.name === 'light' ? '#f4efe6' : colors.accentSoft,
      color: colors.name === 'light' ? '#1f1b14' : colors.textStrong,
      padding: '8px 10px',
      fontSize: '0.8rem',
      fontWeight: 650,
      textDecoration: 'none',
      boxSizing: 'border-box',
      cursor: 'pointer',
      gap: '8px',
    },
    quickNavIcon: {
      display: 'inline-flex',
      alignItems: 'center',
      justifyContent: 'center',
      width: '18px',
      height: '18px',
      flex: '0 0 18px',
    },
    dangerButton: {
      border: `1px solid ${colors.danger}`,
      borderRadius: '8px',
      padding: '9px 12px',
      background: colors.dangerBg,
      color: colors.dangerText,
      cursor: 'pointer',
      fontSize: '0.82rem',
      fontWeight: 700,
    },
    dangerIconButton: {
      width: '34px',
      height: '34px',
      display: 'inline-flex',
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: '8px',
      border: `1px solid ${colors.danger}`,
      background: colors.dangerBg,
      color: colors.dangerText,
      cursor: 'pointer',
      padding: 0,
      flex: '0 0 auto',
    },
    list: {
      display: 'grid',
      gap: '8px',
    },
    listItem: {
      border: `1px solid ${colors.border}`,
      borderRadius: 0,
      padding: '10px',
      background: colors.shellMuted,
      display: 'grid',
      gap: '4px',
    },
    listItemInline: {
      display: 'flex',
      justifyContent: 'space-between',
      alignItems: 'center',
      gap: '8px',
      flexWrap: 'wrap',
      border: `1px solid ${colors.border}`,
      borderRadius: 0,
      padding: '10px',
      background: colors.shellMuted,
    },
    listTitle: {
      margin: 0,
      fontSize: '0.9rem',
      color: colors.textStrong,
      fontWeight: 700,
    },
    smallText: {
      margin: 0,
      fontSize: '0.78rem',
      color: colors.textMuted,
      wordBreak: 'break-word',
    },
    briefingIntro: {
      display: 'grid',
      gap: '12px',
      borderBottom: 'none',
      padding: '0 0 14px',
    },
    briefingIntroHeader: {
      display: 'flex',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
      gap: '12px',
    },
    briefingSubtitle: {
      margin: '6px 0 0',
      color: colors.textMuted,
      fontSize: '0.92rem',
      lineHeight: 1.5,
    },
    briefingBodyText: {
      margin: '8px 0 0',
      color: colors.text,
      fontSize: '0.9rem',
      lineHeight: 1.65,
    },
    briefingList: {
      margin: '8px 0 0',
      paddingLeft: '18px',
      display: 'grid',
      gap: '6px',
      color: colors.text,
      fontSize: '0.88rem',
      lineHeight: 1.55,
    },
    fieldBlock: {
      display: 'grid',
      gap: '10px',
      paddingBottom: '14px',
      borderBottom: 'none',
    },
    fieldHeading: {
      margin: 0,
      fontSize: '1rem',
      color: colors.textStrong,
      lineHeight: 1.45,
      fontWeight: 700,
    },
    fieldPrompt: {
      margin: 0,
      fontSize: '0.94rem',
      color: colors.text,
      lineHeight: 1.6,
      fontWeight: 700,
    },
    fieldDescription: {
      margin: 0,
      fontSize: '0.9rem',
      color: colors.textMuted,
      lineHeight: 1.55,
    },
    tokenBox: {
      border: `1px dashed ${colors.borderAccent}`,
      borderRadius: 0,
      padding: '10px',
      background: colors.tokenBg,
    },
    code: {
      display: 'block',
      fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Consolas, monospace',
      fontSize: '0.8rem',
      color: colors.textStrong,
      wordBreak: 'break-all',
      marginTop: '4px',
    },
    avatarArea: {
      display: 'grid',
      alignItems: 'center',
      justifyItems: 'center',
      gap: '10px',
      padding: '4px 0 8px',
    },
    avatarButton: {
      width: '108px',
      height: '108px',
      borderRadius: '999px',
      border: `1px solid ${colors.borderStrong}`,
      padding: 0,
      position: 'relative',
      background: colors.shellRaised,
      cursor: 'pointer',
      boxShadow: 'none',
    },
    avatarImage: {
      width: '100%',
      height: '100%',
      objectFit: 'cover',
      display: 'block',
      borderRadius: '999px',
    },
    avatarCameraBadge: {
      position: 'absolute',
      right: '-6px',
      bottom: '8px',
      width: '34px',
      height: '34px',
      borderRadius: '999px',
      display: 'grid',
      placeItems: 'center',
      background: colors.shell,
      border: `1px solid ${colors.borderStrong}`,
      boxShadow: 'none',
    },
    avatarGreeting: {
      margin: 0,
      color: colors.textStrong,
      fontSize: '0.98rem',
      fontWeight: 700,
      textAlign: 'center',
    },
    hiddenInput: {
      display: 'none',
    },
    countBadge: {
      width: 'fit-content',
      borderRadius: '999px',
      border: `1px solid ${colors.borderAccent}`,
      padding: '4px 8px',
      fontSize: '0.76rem',
      color: colors.accentMuted,
      background: colors.shell,
      fontWeight: 700,
    },
    uploadDropzone: {
      width: '100%',
      minHeight: '142px',
      border: `1px dashed ${colors.borderStrong}`,
      borderRadius: '12px',
      background: colors.inputBg,
      color: colors.textMuted,
      display: 'grid',
      placeItems: 'center',
      gap: '10px',
      padding: '18px',
      cursor: 'pointer',
      textAlign: 'center',
      boxSizing: 'border-box',
    },
    uploadIconFrame: {
      width: '58px',
      height: '58px',
      display: 'grid',
      placeItems: 'center',
      borderRadius: 0,
      background: colors.shell,
      border: `1px solid ${colors.border}`,
    },
    uploadDropzoneText: {
      fontSize: '0.86rem',
      color: colors.textMuted,
      lineHeight: 1.5,
    },
    uploadPrimaryButton: {
      border: `1px solid ${colors.borderStrong}`,
      borderRadius: '8px',
      padding: '8px 10px',
      background: colors.name === 'light' ? '#f4efe6' : colors.shellMuted,
      color: colors.name === 'light' ? '#1f1b14' : colors.textStrong,
      cursor: 'pointer',
      fontWeight: 700,
      fontSize: '0.82rem',
    },
    uploadBrowseText: {
      color: colors.accentMuted,
      fontWeight: 800,
      textDecoration: 'underline',
    },
    uploadSelectedFile: {
      display: 'flex',
      alignItems: 'center',
      gap: '10px',
      border: `1px solid ${colors.border}`,
      borderRadius: 0,
      padding: '10px',
      background: colors.shellMuted,
    },
    uploadFileIcon: {
      width: '42px',
      height: '42px',
      border: `1px solid ${colors.borderStrong}`,
      borderRadius: 0,
      display: 'grid',
      placeItems: 'center',
      color: colors.textMuted,
      fontSize: '0.62rem',
      fontWeight: 800,
      background: colors.shell,
    },
    uploadFileDetails: {
      minWidth: 0,
      display: 'grid',
      gap: '3px',
    },
    entryButton: {
      border: `1px solid ${colors.border}`,
      borderRadius: 0,
      padding: '10px',
      background: colors.name === 'light' ? '#ffffff' : colors.shellMuted,
      color: colors.text,
      display: 'grid',
      gap: '4px',
      cursor: 'pointer',
      textAlign: 'left',
    },
    entryButtonActive: {
      border: `1px solid ${colors.borderAccent}`,
      borderRadius: 0,
      padding: '10px',
      background: colors.name === 'light' ? '#ffffff' : colors.accentSoft,
      color: colors.text,
      display: 'grid',
      gap: '4px',
      cursor: 'pointer',
      textAlign: 'left',
    },
    entryBadge: {
      border: `1px solid ${colors.borderAccent}`,
      borderRadius: '999px',
      padding: '1px 8px',
      fontSize: '0.7rem',
      color: colors.accentMuted,
      background: colors.shell,
    },
    sidebarSection: {
      borderTop: 'none',
      paddingTop: 0,
      display: 'grid',
      gap: '6px',
    },
    sidebarSectionTitle: {
      margin: 0,
      fontSize: '0.72rem',
      color: colors.textMuted,
      fontWeight: 650,
      letterSpacing: '0.06em',
      textTransform: 'uppercase',
    },
    sidebarFooter: {
      marginTop: 'auto',
      paddingTop: 0,
      borderTop: 'none',
      display: 'flex',
      gap: '8px',
    },
    mainArea: {
      minWidth: 0,
      marginLeft: 0,
      display: 'grid',
      minHeight: '100%',
      background: colors.name === 'light' ? 'var(--planto-light-view-bg)' : colors.pageBackground,
    },
    mobileOverlay: {
      position: 'fixed',
      inset: 0,
      background: colors.overlay,
      zIndex: 24,
    },
    mobileDrawer: {
      position: 'fixed',
      top: '0',
      left: '0',
      width: 'min(90vw, 360px)',
      height: '100vh',
      background: colors.shell,
      borderRight: `1px solid ${colors.border}`,
      padding: '10px',
      overflow: 'auto',
      zIndex: 30,
      display: 'grid',
      gap: '10px',
    },
  };
}
