import type { DashboardStyles, DashboardThemeColors } from '../../types/dashboard';

export const themeTokens: Record<'dark' | 'light', DashboardThemeColors> = {
  dark: {
    name: 'dark',
    pageBackground: 'var(--planto-page-bg)',
    shell: 'var(--planto-surface)',
    shellMuted: 'var(--planto-surface-muted)',
    shellRaised: 'var(--planto-surface-raised)',
    surfaceBase: 'rgba(10, 17, 14, 0.78)',
    surfaceRaised: 'rgba(13, 22, 18, 0.9)',
    surfaceSoft: 'rgba(15, 24, 20, 0.82)',
    surfaceStrong: 'rgba(8, 14, 11, 0.84)',
    border: 'var(--planto-border)',
    borderStrong: 'var(--planto-border-strong)',
    borderAccent: 'var(--planto-border-accent)',
    text: 'var(--planto-text)',
    textMuted: 'var(--planto-muted)',
    textStrong: 'var(--planto-text-strong)',
    accent: 'var(--planto-accent)',
    accentText: 'var(--planto-accent-text)',
    accentSoft: 'var(--planto-accent-soft)',
    accentMuted: 'var(--planto-accent-muted)',
    danger: 'var(--planto-danger)',
    dangerBg: 'var(--planto-danger-bg)',
    dangerText: 'var(--planto-danger-text)',
    successBg: 'var(--planto-success-bg)',
    successText: 'var(--planto-success-text)',
    errorBg: 'var(--planto-error-bg)',
    errorText: 'var(--planto-error-text)',
    overlay: 'var(--planto-overlay)',
    inputBg: 'var(--planto-input-bg)',
    tokenBg: 'var(--planto-token-bg)',
    progressTrack: 'rgba(255,255,255,0.08)',
    progressFill: 'var(--planto-accent)',
    statusMuted: 'rgba(142, 230, 189, 0.58)',
    statusActive: 'var(--planto-accent)',
    statusWarning: 'rgba(142, 230, 189, 0.82)',
    statusDanger: 'rgba(255, 209, 209, 0.88)',
    statusMutedSoft: 'rgba(67, 201, 137, 0.08)',
    statusActiveSoft: 'rgba(67, 201, 137, 0.16)',
    statusWarningSoft: 'rgba(67, 201, 137, 0.12)',
    statusDangerSoft: 'rgba(92, 19, 19, 0.42)',
    statusMutedText: 'var(--planto-muted)',
    statusActiveText: 'var(--planto-accent-muted)',
    statusWarningText: 'var(--planto-text)',
    statusDangerText: 'var(--planto-danger-text)',
  },
  light: {
    name: 'light',
    pageBackground: '#f6f3ed',
    shell: '#f6f3ed',
    shellMuted: '#f6f3ed',
    shellRaised: '#fbf9f5',
    surfaceBase: 'rgba(255, 255, 255, 0.82)',
    surfaceRaised: 'rgba(248, 252, 249, 0.92)',
    surfaceSoft: 'rgba(255,255,255,0.76)',
    surfaceStrong: 'rgba(255,255,255,0.9)',
    border: 'var(--planto-light-border)',
    borderStrong: 'var(--planto-light-border-strong)',
    borderAccent: 'var(--planto-light-border-accent)',
    text: 'var(--planto-light-text)',
    textMuted: 'var(--planto-light-muted)',
    textStrong: 'var(--planto-light-text-strong)',
    accent: 'var(--planto-light-accent)',
    accentText: 'var(--planto-light-accent-text)',
    accentSoft: 'var(--planto-light-accent-soft)',
    accentMuted: 'var(--planto-light-accent-muted)',
    danger: 'var(--planto-light-danger)',
    dangerBg: 'var(--planto-light-danger-bg)',
    dangerText: 'var(--planto-light-danger-text)',
    successBg: 'var(--planto-light-success-bg)',
    successText: 'var(--planto-light-success-text)',
    errorBg: 'var(--planto-light-error-bg)',
    errorText: 'var(--planto-light-error-text)',
    overlay: 'var(--planto-light-overlay)',
    inputBg: 'var(--planto-light-input-bg)',
    tokenBg: 'var(--planto-light-token-bg)',
    progressTrack: 'rgba(17, 32, 25, 0.08)',
    progressFill: 'var(--planto-light-accent)',
    statusMuted: 'rgba(37, 135, 90, 0.64)',
    statusActive: 'var(--planto-light-accent)',
    statusWarning: 'rgba(17, 32, 25, 0.72)',
    statusDanger: 'var(--planto-light-danger-text)',
    statusMutedSoft: 'rgba(67, 201, 137, 0.08)',
    statusActiveSoft: 'rgba(232, 255, 241, 0.86)',
    statusWarningSoft: 'rgba(245, 251, 247, 0.96)',
    statusDangerSoft: 'rgba(255, 232, 232, 0.96)',
    statusMutedText: 'var(--planto-light-muted)',
    statusActiveText: 'var(--planto-light-accent-muted)',
    statusWarningText: 'var(--planto-light-text)',
    statusDangerText: 'var(--planto-light-danger-text)',
  },
};

export function createDashboardStyles(colors: DashboardThemeColors, viewportWidth: number): DashboardStyles {
  const isCompact = viewportWidth < 980;
  const isWide = viewportWidth >= 1280;
  const isMedium = viewportWidth >= 980 && viewportWidth < 1280;
  const typeScale = {
    h1: isCompact ? '1.5rem' : '1.6rem',
    h2: '1.12rem',
    h3: '1rem',
    body: '0.92rem',
    small: '0.82rem',
    meta: '0.75rem',
  };
  const cardShadow =
    colors.name === 'light'
      ? '0 20px 36px rgba(13, 35, 24, 0.07)'
      : '0 20px 36px rgba(0, 0, 0, 0.24)';
  const raisedShadow =
    colors.name === 'light'
      ? '0 24px 48px rgba(13, 35, 24, 0.08)'
      : '0 24px 48px rgba(0, 0, 0, 0.28)';

  return {
    page: {
      minHeight: '100vh',
      background: colors.pageBackground,
      color: colors.text,
      padding: 0,
      fontFamily: '"Inter", "Segoe UI", -apple-system, BlinkMacSystemFont, sans-serif',
      position: 'relative',
    },
    pageShell: {
      maxWidth: isWide ? '1360px' : '1120px',
      margin: '0 auto',
      display: 'grid',
      gap: isCompact ? '14px' : '18px',
      padding: isCompact ? '12px' : '24px',
      width: '100%',
      boxSizing: 'border-box',
    },
    header: {
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'space-between',
      flexDirection: 'row',
      gap: '14px',
      background: colors.surfaceSoft,
      border: `1px solid ${colors.border}`,
      borderRadius: '24px',
      padding: isCompact ? '12px 14px' : '16px 18px',
      boxShadow: raisedShadow,
      backdropFilter: 'blur(18px)',
      position: 'sticky',
      top: 0,
      zIndex: 10,
    },
    headerLeading: {
      display: 'flex',
      alignItems: 'center',
      gap: '12px',
      minWidth: 0,
    },
    title: {
      margin: 0,
      fontSize: isCompact ? '1.16rem' : '1.32rem',
      color: colors.textStrong,
      fontWeight: 700,
      letterSpacing: '-0.03em',
      whiteSpace: 'nowrap',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    subtitle: { margin: '6px 0 0', color: colors.textMuted, fontSize: typeScale.body },
    headerActions: {
      display: 'flex',
      gap: '8px',
      alignItems: 'center',
      width: 'auto',
      justifyContent: 'flex-end',
      flexWrap: 'nowrap',
    },
    headerTokenBar: {
      display: 'inline-flex',
      alignItems: 'center',
      gap: '8px',
      border: `1px solid ${colors.borderStrong}`,
      borderRadius: '8px',
      padding: '6px',
      background: colors.inputBg,
      width: '100%',
      maxWidth: '100%',
      minWidth: 0,
      boxSizing: 'border-box',
    },
    headerTokenCode: {
      flex: '0 1 auto',
      minWidth: 0,
      maxWidth: '100%',
      borderRadius: '6px',
      padding: '8px 9px',
      background: colors.tokenBg,
      color: colors.textStrong,
      fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Consolas, monospace',
      fontSize: typeScale.meta,
      whiteSpace: 'nowrap',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    headerTokenHint: {
      flex: '0 1 auto',
      minWidth: 0,
      maxWidth: '100%',
      borderRadius: '6px',
      padding: '8px 9px',
      color: colors.textMuted,
      fontSize: typeScale.small,
      whiteSpace: 'nowrap',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    toastViewport: {
      position: 'fixed',
      left: '50%',
      bottom: isCompact ? '16px' : '24px',
      transform: 'translateX(-50%)',
      zIndex: 50,
      display: 'grid',
      gap: '10px',
      width: `min(${isCompact ? 'calc(100vw - 24px)' : '420px'}, calc(100vw - 24px))`,
      pointerEvents: 'none',
    },
    notice: {
      borderRadius: '12px',
      padding: '12px 14px',
      background: colors.successBg,
      color: colors.successText,
      fontSize: typeScale.body,
      fontWeight: 700,
      border: 'none',
      boxShadow: colors.name === 'light' ? '0 14px 30px rgba(31, 27, 20, 0.12)' : '0 14px 30px rgba(0, 0, 0, 0.34)',
      pointerEvents: 'auto',
    },
    errorBanner: {
      borderRadius: '12px',
      padding: '12px 14px',
      background: colors.errorBg,
      color: colors.errorText,
      border: 'none',
      fontSize: typeScale.body,
      fontWeight: 700,
      boxShadow: colors.name === 'light' ? '0 14px 30px rgba(31, 27, 20, 0.12)' : '0 14px 30px rgba(0, 0, 0, 0.34)',
      pointerEvents: 'auto',
    },
    loader: {
      padding: '18px 0',
      color: colors.textMuted,
      fontSize: typeScale.body,
    },
    workspace: {
      display: 'grid',
      gap: isCompact ? '8px' : '10px',
      gridTemplateColumns: isWide
        ? 'minmax(300px, 380px) minmax(0, 1fr) minmax(300px, 380px)'
        : isMedium
        ? 'minmax(0, 1.6fr) minmax(320px, 1fr)'
        : 'minmax(0, 1fr)',
      alignItems: 'start',
      position: 'relative',
      minHeight: 'calc(100vh - 22px)',
    },
    zoneNav: {
      display: 'grid',
      gap: '12px',
      alignSelf: 'start',
      position: isCompact ? 'static' : 'sticky',
      top: isCompact ? 'auto' : '10px',
      minWidth: 0,
      gridColumn: isWide ? '1' : isMedium ? '2' : '1',
      maxHeight: isCompact ? 'none' : 'calc(100dvh - 20px)',
      overflowY: isCompact ? 'visible' : 'auto',
      overflowX: 'hidden',
      paddingRight: 0,
      paddingBottom: isCompact ? 0 : '12px',
    },
    zoneMain: {
      display: 'grid',
      gap: '12px',
      minWidth: 0,
      alignSelf: 'stretch',
      gridColumn: isWide ? '2' : '1',
    },
    mainPanelScroll: {
      display: 'grid',
      gap: '12px',
      minHeight: 0,
      maxHeight: isCompact ? 'none' : 'calc(100vh - 132px)',
      overflowY: isCompact ? 'visible' : 'auto',
      overflowX: 'hidden',
      paddingRight: isCompact ? 0 : '4px',
    },
    zoneSupport: {
      display: 'grid',
      gap: '12px',
      minWidth: 0,
      alignSelf: 'start',
      position: isCompact ? 'static' : 'sticky',
      top: isCompact ? 'auto' : '10px',
      gridColumn: isWide ? '3' : isMedium ? '2' : '1',
    },
    grid: {
      display: 'grid',
      gap: isCompact ? '10px' : '14px',
      gridTemplateColumns: '1fr',
      alignItems: 'start',
      position: 'relative',
    },
    singleDashboardGrid: {
      display: 'grid',
      gap: isCompact ? '12px' : '16px',
      gridTemplateColumns: isWide ? 'minmax(0, 1.52fr) minmax(320px, 0.72fr)' : 'minmax(0, 1fr)',
      alignItems: 'start',
    },
    singleDashboardMain: {
      display: 'grid',
      gap: isCompact ? '10px' : '12px',
      minWidth: 0,
    },
    singleDashboardSide: {
      display: 'grid',
      gap: isCompact ? '10px' : '12px',
      minWidth: 0,
      position: isWide ? 'sticky' : 'static',
      top: isWide ? '10px' : 'auto',
    },
    singleDashboardWideCard: {
      border: `1px solid ${colors.border}`,
      borderRadius: '28px',
      background: colors.surfaceBase,
      padding: isCompact ? '18px' : '22px',
      display: 'grid',
      gap: '16px',
      minWidth: 0,
      boxShadow: raisedShadow,
      backdropFilter: 'blur(16px)',
    },
    leftPanel: {
      background: colors.name === 'light' ? '#ffffff' : colors.shell,
      border: 'none',
      borderRadius: '10px',
      padding: '12px',
      display: 'grid',
      gap: '10px',
      maxHeight: 'none',
      overflow: 'auto',
      position: 'static',
      width: '100%',
    },
    centerPanel: {
      background: 'transparent',
      border: 'none',
      borderRadius: '10px',
      padding: 0,
      display: 'grid',
      gap: '12px',
      minHeight: 0,
    },
    rightColumn: {
      display: 'grid',
      gap: '14px',
      alignSelf: 'start',
    },
    rightPanel: {
      background: 'transparent',
      border: 'none',
      borderRadius: 0,
      padding: 0,
      display: 'grid',
      gap: '10px',
    },
    panelCard: {
      border: `1px solid ${colors.border}`,
      borderRadius: '24px',
      background: colors.surfaceBase,
      boxShadow: cardShadow,
      padding: isCompact ? '16px' : '18px',
      display: 'grid',
      gap: '14px',
      minWidth: 0,
      backdropFilter: 'blur(16px)',
    },
    panelCardHeader: {
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: '12px',
      borderBottom: `1px solid ${colors.border}`,
      minHeight: '48px',
      padding: '0 0 12px',
    },
    panelCardHeaderGroup: {
      display: 'inline-flex',
      alignItems: 'center',
      gap: '6px',
      marginLeft: 'auto',
    },
    cardIconButton: {
      width: '36px',
      height: '36px',
      minWidth: '36px',
      display: 'inline-flex',
      alignItems: 'center',
      justifyContent: 'center',
      border: `1px solid ${colors.borderStrong}`,
      borderRadius: '12px',
      padding: 0,
      background: colors.surfaceSoft,
      color: colors.text,
      cursor: 'pointer',
      fontSize: typeScale.small,
      fontWeight: 700,
      lineHeight: 1,
      boxShadow: `inset 0 0 0 1px ${colors.border}`,
    },
    mainTabs: {
      display: 'inline-flex',
      gap: '4px',
      flexWrap: 'nowrap',
      alignItems: 'center',
      border: 'none',
      borderRadius: '999px',
      background: colors.name === 'light' ? '#ebe9e3' : colors.shellMuted,
      padding: '4px',
      width: 'fit-content',
      maxWidth: '100%',
      overflowX: 'auto',
    },
    mainTabButton: {
      border: 'none',
      borderRadius: '999px',
      padding: '8px 16px',
      background: 'transparent',
      color: colors.textMuted,
      cursor: 'pointer',
      fontWeight: 500,
      fontSize: typeScale.small,
      whiteSpace: 'nowrap',
      minHeight: '32px',
    },
    mainTabActive: {
      border: 'none',
      borderRadius: '999px',
      padding: '8px 16px',
      background: colors.name === 'light' ? '#ffffff' : 'var(--planto-nav-active)',
      color: colors.textStrong,
      cursor: 'pointer',
      fontWeight: 600,
      fontSize: typeScale.small,
      whiteSpace: 'nowrap',
      minHeight: '32px',
    },
    panelTitle: {
      margin: 0,
      color: colors.textStrong,
      fontSize: isCompact ? '1rem' : '1.08rem',
      fontWeight: 700,
      lineHeight: 1.2,
      letterSpacing: '-0.02em',
    },
    cardBlock: {
      border: 'none',
      borderRadius: 0,
      padding: 0,
      background: 'transparent',
      display: 'grid',
      gap: '8px',
    },
    formCard: {
      border: `1px solid ${colors.border}`,
      borderRadius: '18px',
      background: colors.surfaceRaised,
      padding: '16px',
    },
    formCardHeader: {
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: '10px',
      padding: 0,
    },
    formCardBody: {
      display: 'grid',
      gap: '18px',
      borderTop: `1px solid ${colors.border}`,
      padding: '14px 0 0',
    },
    cardTitle: { margin: 0, fontSize: typeScale.h3, color: colors.textStrong },
    sectionDescription: {
      margin: '2px 0 0',
      color: colors.textMuted,
      fontSize: typeScale.body,
      lineHeight: 1.5,
    },
    collapseButton: {
      width: '34px',
      height: '34px',
      display: 'inline-flex',
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: '10px',
      border: `1px solid ${colors.borderStrong}`,
      background: colors.shell,
      cursor: 'pointer',
      padding: 0,
    },
    formGrid: {
      display: 'grid',
      gap: '12px',
      gridTemplateColumns: '1fr',
      alignItems: 'start',
    },
    profileGridTwo: {
      display: 'grid',
      gap: '12px',
      gridTemplateColumns: isCompact ? '1fr' : 'repeat(2, minmax(0, 1fr))',
      alignItems: 'start',
    },
    profileGridThree: {
      display: 'grid',
      gap: '12px',
      gridTemplateColumns: isCompact ? '1fr' : 'repeat(3, minmax(0, 1fr))',
      alignItems: 'start',
    },
    label: {
      display: 'grid',
      gap: '8px',
      fontSize: typeScale.meta,
      color: colors.textMuted,
      letterSpacing: '0.04em',
      textTransform: 'uppercase',
      fontWeight: 700,
    },
    input: {
      border: `1px solid ${colors.borderStrong}`,
      borderRadius: '14px',
      background: colors.surfaceStrong,
      color: colors.text,
      padding: '12px 14px',
      fontSize: typeScale.body,
      width: '100%',
      outline: 'none',
      boxSizing: 'border-box',
      boxShadow: `inset 0 0 0 1px ${colors.border}`,
    },
    profileInput: {
      border: `1px solid ${colors.borderStrong}`,
      borderRadius: '14px',
      background: colors.surfaceSoft,
      color: colors.text,
      padding: '12px 14px',
      fontSize: typeScale.body,
      width: '100%',
      outline: 'none',
      boxSizing: 'border-box',
      boxShadow: `inset 0 0 0 1px ${colors.border}`,
    },
    textarea: {
      border: `1px solid ${colors.borderStrong}`,
      borderRadius: '16px',
      background: colors.surfaceStrong,
      color: colors.text,
      padding: '12px 14px',
      fontSize: typeScale.body,
      width: '100%',
      resize: 'vertical',
      outline: 'none',
      boxSizing: 'border-box',
      minHeight: '92px',
      boxShadow: `inset 0 0 0 1px ${colors.border}`,
    },
    primaryButton: {
      border: `1px solid ${colors.borderAccent}`,
      borderRadius: '14px',
      padding: '11px 14px',
      background: colors.accent,
      color: colors.accentText,
      cursor: 'pointer',
      fontWeight: 700,
      fontSize: typeScale.small,
      boxShadow:
        colors.name === 'light'
          ? '0 12px 24px rgba(67, 201, 137, 0.18)'
          : '0 12px 24px rgba(67, 201, 137, 0.16)',
    },
    secondaryButton: {
      border: `1px solid ${colors.borderStrong}`,
      borderRadius: '14px',
      padding: '11px 14px',
      background: colors.surfaceSoft,
      color: colors.text,
      cursor: 'pointer',
      fontWeight: 700,
      fontSize: typeScale.small,
    },
    ghostButton: {
      border: `1px solid ${colors.borderStrong}`,
      borderRadius: '8px',
      padding: '8px 10px',
      background: colors.name === 'light' ? '#ffffff' : 'transparent',
      color: colors.text,
      cursor: 'pointer',
      fontSize: typeScale.small,
      fontWeight: 600,
    },
    iconButton: {
      display: 'inline-flex',
      alignItems: 'center',
      gap: '8px',
      border: `1px solid ${colors.borderStrong}`,
      borderRadius: '8px',
      padding: '8px 10px',
      background: colors.name === 'light' ? '#ffffff' : colors.shell,
      color: colors.text,
      cursor: 'pointer',
      fontSize: typeScale.small,
      fontWeight: 600,
    },
    iconOnlyButton: {
      width: '34px',
      height: '34px',
      minWidth: '34px',
      flex: '0 0 34px',
      display: 'inline-flex',
      alignItems: 'center',
      justifyContent: 'center',
      border: `1px solid ${colors.borderStrong}`,
      borderRadius: '8px',
      padding: 0,
      background: colors.name === 'light' ? '#ffffff' : colors.shell,
      color: colors.text,
      cursor: 'pointer',
    },
    quickNav: {
      display: 'grid',
      gridTemplateColumns: '1fr',
      gap: 0,
      width: '100%',
      maxWidth: '100%',
      borderTop: `1px solid ${colors.border}`,
    },
    quickNavLink: {
      display: 'inline-flex',
      alignItems: 'center',
      justifyContent: 'flex-start',
      width: '100%',
      minHeight: '36px',
      borderRadius: 0,
      border: 'none',
      borderBottom: `1px solid ${colors.border}`,
      background: 'transparent',
      color: colors.name === 'light' ? '#1f1b14' : colors.text,
      padding: '8px 10px',
      fontSize: typeScale.small,
      fontWeight: 600,
      textDecoration: 'none',
      boxSizing: 'border-box',
      cursor: 'pointer',
      gap: '8px',
    },
    quickNavLinkActive: {
      display: 'inline-flex',
      alignItems: 'center',
      justifyContent: 'flex-start',
      width: '100%',
      minHeight: '36px',
      borderRadius: 0,
      border: 'none',
      borderBottom: `1px solid ${colors.border}`,
      background: colors.name === 'light' ? '#f4efe6' : colors.accentSoft,
      color: colors.name === 'light' ? '#1f1b14' : colors.textStrong,
      padding: '8px 10px',
      fontSize: typeScale.small,
      fontWeight: 650,
      textDecoration: 'none',
      boxSizing: 'border-box',
      cursor: 'pointer',
      gap: '8px',
    },
    quickNavIcon: {
      display: 'inline-flex',
      alignItems: 'center',
      justifyContent: 'center',
      width: '18px',
      height: '18px',
      flex: '0 0 18px',
    },
    dangerButton: {
      border: `1px solid ${colors.danger}`,
      borderRadius: '8px',
      padding: '9px 12px',
      background: colors.dangerBg,
      color: colors.dangerText,
      cursor: 'pointer',
      fontSize: typeScale.small,
      fontWeight: 700,
    },
    dangerIconButton: {
      width: '38px',
      height: '38px',
      display: 'inline-flex',
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: '12px',
      border: `1px solid ${colors.danger}`,
      background: colors.dangerBg,
      color: colors.dangerText,
      cursor: 'pointer',
      padding: 0,
      flex: '0 0 auto',
    },
    list: {
      display: 'grid',
      gap: '8px',
    },
    attachmentListContainer: {
      display: 'grid',
      border: `1px solid ${colors.border}`,
      borderRadius: '18px',
      background: colors.surfaceRaised,
      overflow: 'hidden',
    },
    attachmentListRow: {
      display: 'flex',
      alignItems: 'center',
      gap: '10px',
      minWidth: 0,
      padding: '10px',
    },
    attachmentFileName: {
      margin: 0,
      minWidth: 0,
      flex: '1 1 auto',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
      whiteSpace: 'nowrap',
      color: colors.text,
      fontSize: typeScale.small,
      fontWeight: 400,
    },
    listItem: {
      border: `1px solid ${colors.border}`,
      borderRadius: 0,
      padding: '10px',
      background: colors.shellMuted,
      display: 'grid',
      gap: '4px',
    },
    listItemInline: {
      display: 'flex',
      justifyContent: 'space-between',
      alignItems: 'center',
      gap: '8px',
      flexWrap: 'wrap',
      border: 'none',
      borderRadius: 0,
      padding: 0,
      background: 'transparent',
    },
    listTitle: {
      margin: 0,
      fontSize: typeScale.h3,
      color: colors.textStrong,
      fontWeight: 700,
    },
    smallText: {
      margin: 0,
      fontSize: typeScale.small,
      color: colors.textMuted,
      wordBreak: 'break-word',
    },
    bodyText: {
      margin: 0,
      fontSize: typeScale.body,
      color: colors.text,
      lineHeight: 1.65,
    },
    fieldBlock: {
      display: 'grid',
      gap: '10px',
      border: `1px solid ${colors.border}`,
      borderRadius: '10px',
      background: colors.surfaceStrong,
      padding: '14px',
    },
    fieldHeading: {
      margin: 0,
      fontSize: typeScale.h3,
      color: colors.textStrong,
      lineHeight: 1.3,
      fontWeight: 800,
      letterSpacing: '0.01em',
    },
    fieldPrompt: {
      margin: 0,
      fontSize: typeScale.h3,
      color: colors.text,
      lineHeight: 1.55,
      fontWeight: 700,
    },
    fieldDescription: {
      margin: 0,
      fontSize: typeScale.body,
      color: colors.textMuted,
      lineHeight: 1.5,
    },
    tokenBox: {
      border: `1px dashed ${colors.borderAccent}`,
      borderRadius: 0,
      padding: '10px',
      background: colors.tokenBg,
    },
    code: {
      display: 'block',
      fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Consolas, monospace',
      fontSize: typeScale.small,
      color: colors.textStrong,
      wordBreak: 'break-all',
      marginTop: '4px',
    },
    avatarArea: {
      display: 'grid',
      alignItems: 'center',
      justifyItems: 'start',
      gap: '12px',
      padding: '4px 0 10px',
    },
    avatarButton: {
      width: '118px',
      height: '118px',
      borderRadius: '999px',
      border: `1px solid ${colors.borderAccent}`,
      padding: 0,
      position: 'relative',
      background: colors.shellRaised,
      cursor: 'pointer',
      boxShadow:
        colors.name === 'light'
          ? '0 18px 34px rgba(13, 35, 24, 0.12)'
          : '0 18px 34px rgba(0, 0, 0, 0.3)',
    },
    avatarImage: {
      width: '100%',
      height: '100%',
      objectFit: 'cover',
      display: 'block',
      borderRadius: '999px',
    },
    avatarCameraBadge: {
      position: 'absolute',
      right: '-6px',
      bottom: '8px',
      width: '40px',
      height: '40px',
      borderRadius: '999px',
      display: 'grid',
      placeItems: 'center',
      background: colors.accent,
      border: `1px solid ${colors.borderAccent}`,
      boxShadow:
        colors.name === 'light'
          ? '0 12px 20px rgba(67, 201, 137, 0.18)'
          : '0 12px 20px rgba(67, 201, 137, 0.18)',
    },
    avatarGreeting: {
      margin: 0,
      color: colors.textStrong,
      fontSize: typeScale.h3,
      fontWeight: 700,
      textAlign: 'left',
    },
    hiddenInput: {
      display: 'none',
    },
    countBadge: {
      width: 'fit-content',
      borderRadius: '999px',
      border: `1px solid ${colors.borderAccent}`,
      padding: '6px 10px',
      fontSize: typeScale.meta,
      color: colors.accentMuted,
      background: colors.accentSoft,
      fontWeight: 700,
      letterSpacing: '0.04em',
      textTransform: 'uppercase',
    },
    uploadDropzone: {
      width: '100%',
      minHeight: '142px',
      border: `1px dashed ${colors.borderAccent}`,
      borderRadius: '22px',
      background: colors.inputBg,
      color: colors.textMuted,
      display: 'grid',
      placeItems: 'center',
      gap: '14px',
      padding: '22px',
      cursor: 'pointer',
      textAlign: 'center',
      boxSizing: 'border-box',
      boxShadow: `inset 0 0 0 1px ${colors.border}`,
    },
    uploadIconFrame: {
      width: '62px',
      height: '62px',
      display: 'grid',
      placeItems: 'center',
      borderRadius: '18px',
      background: colors.accentSoft,
      border: `1px solid ${colors.border}`,
    },
    uploadDropzoneText: {
      fontSize: typeScale.body,
      color: colors.textMuted,
      lineHeight: 1.5,
    },
    uploadPrimaryButton: {
      border: `1px solid ${colors.borderAccent}`,
      borderRadius: '14px',
      padding: '11px 14px',
      background: colors.accentSoft,
      color: colors.textStrong,
      cursor: 'pointer',
      fontWeight: 700,
      fontSize: typeScale.small,
    },
    uploadBrowseText: {
      color: colors.accentMuted,
      fontWeight: 800,
      textDecoration: 'underline',
    },
    uploadSelectedFile: {
      display: 'flex',
      alignItems: 'center',
      gap: '10px',
      border: `1px solid ${colors.border}`,
      borderRadius: '18px',
      padding: '12px',
      background: colors.surfaceRaised,
    },
    uploadFileIcon: {
      width: '42px',
      height: '42px',
      border: `1px solid ${colors.borderStrong}`,
      borderRadius: '12px',
      display: 'grid',
      placeItems: 'center',
      color: colors.textMuted,
      fontSize: '0.62rem',
      fontWeight: 800,
      background: colors.shell,
    },
    uploadFileDetails: {
      minWidth: 0,
      display: 'grid',
      gap: '3px',
    },
    entryButton: {
      border: `1px solid ${colors.border}`,
      borderRadius: '18px',
      padding: '14px',
      background: colors.surfaceSoft,
      color: colors.text,
      display: 'grid',
      gap: '8px',
      cursor: 'pointer',
      textAlign: 'left',
    },
    entryButtonActive: {
      border: `1px solid ${colors.borderAccent}`,
      borderRadius: '18px',
      padding: '14px',
      background: colors.name === 'light' ? 'rgba(232, 255, 241, 0.86)' : colors.accentSoft,
      color: colors.text,
      display: 'grid',
      gap: '8px',
      cursor: 'pointer',
      textAlign: 'left',
      boxShadow: `inset 0 0 0 1px ${colors.borderAccent}`,
    },
    entryBadge: {
      border: `1px solid ${colors.borderAccent}`,
      borderRadius: '999px',
      padding: '4px 9px',
      fontSize: typeScale.meta,
      color: colors.accentMuted,
      background: colors.accentSoft,
      letterSpacing: '0.04em',
      textTransform: 'uppercase',
    },
    documentPreview: {
      margin: 0,
      border: `1px solid ${colors.border}`,
      borderRadius: '18px',
      background: colors.surfaceRaised,
      color: colors.text,
      padding: '16px',
      fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Consolas, monospace',
      fontSize: typeScale.small,
      lineHeight: 1.55,
      whiteSpace: 'pre-wrap',
      wordBreak: 'break-word',
      maxHeight: isCompact ? '320px' : '460px',
      overflow: 'auto',
    },
    sidebarSection: {
      borderTop: 'none',
      paddingTop: 0,
      display: 'grid',
      gap: '6px',
    },
    sidebarSectionTitle: {
      margin: 0,
      fontSize: typeScale.meta,
      color: colors.textMuted,
      fontWeight: 650,
      letterSpacing: '0.06em',
      textTransform: 'uppercase',
    },
    sidebarFooter: {
      marginTop: 'auto',
      paddingTop: 0,
      borderTop: 'none',
      display: 'flex',
      gap: '8px',
    },
    mainArea: {
      minWidth: 0,
      marginLeft: 0,
      display: 'grid',
      minHeight: '100%',
      background: colors.name === 'light' ? 'var(--planto-light-view-bg)' : colors.pageBackground,
    },
    mobileOverlay: {
      position: 'fixed',
      inset: 0,
      background: colors.overlay,
      zIndex: 24,
    },
    mobileDrawer: {
      position: 'fixed',
      top: '0',
      left: '0',
      width: 'min(90vw, 360px)',
      height: '100vh',
      background: colors.shell,
      borderRight: `1px solid ${colors.border}`,
      padding: '10px',
      overflow: 'auto',
      zIndex: 30,
      display: 'grid',
      gap: '10px',
    },
  };
}
